###  Login untuk Mendapatkan accessToken
POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"bharada_e",
    "password":"fer303"
}

### Get user dengan menginputkan accessToken yang didapat dari proses Login Diatas
GET http://localhost:8000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXJhZGFfZSIsInBhc3N3b3JkIjoiZmVyMzAzIiwidXNlcklkIjozLCJpYXQiOjE2NjIzNTkzNDksImV4cCI6MTY2MjM1OTM3OX0.rf6EcmfRZTt3tKAVbqLri0dbNE8d-so_ImPqd6AnWR8


### Get Users dengan menginputkan accessToken yang didapat dari proses Login Diatas
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXJhZGFfZSIsInBhc3N3b3JkIjoiZmVyMzAzIiwidXNlcklkIjozLCJpYXQiOjE2NjIzNTkzNDksImV4cCI6MTY2MjM1OTM3OX0.rf6EcmfRZTt3tKAVbqLri0dbNE8d-so_ImPqd6AnWR8


###  Register user, menambahkan user di folder app/models/users.json
POST http://localhost:8000/register
Content-Type: application/json

{
    "username":"sinaga",
    "password":"fer303"
}


