###  Login untuk Mendapatkan Token
POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"bharada_e",
    "password":"fer303"
}

### Get user dengan menginputkan accessToken yang didapat dari proses Login Diatas
GET http://localhost:8000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXJhZGFfZSIsInBhc3N3b3JkIjoiZmVyMzAzIiwidXNlcklkIjozLCJpYXQiOjE2NjIyMjE5OTIsImV4cCI6MTY2MjIyMjAyMn0.UC7fa2_YhvF8etTC1dHLUgxq5Bem6UboteAmC0W-LTk


### Get Users dengan menginputkan accessToken yang didapat dari proses Login Diatas
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJoYXJhZGFfZSIsInBhc3N3b3JkIjoiZmVyMzAzIiwidXNlcklkIjozLCJpYXQiOjE2NjIyMjEyNjYsImV4cCI6MTY2MjIyMTI5Nn0.haSRp7pddlIxXQjUsxknbfDseKvk1WIJCzA9iUriYHc


###  Register user, menambahkan user di folder app/models/users.json
POST http://localhost:8000/register
Content-Type: application/json

{
    "username":"sinaga",
    "password":"fer303"
}


